apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-prometheus
spec:
  rules:
  - http:
        paths:
        - path: /
          backend:
             serviceName: prometheus
             servicePort: 8080
