apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "2"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://10.0.2.15:32553
    - name: Loki
      type: loki
      access: proxy
      url: http://10.0.2.15:31670
      editable: false
