apiVersion: v1
kind: Namespace
metadata:
    name: monitoring
---
apiVersion: v1
kind: Service
metadata:
    name: grafana
    namespace: monitoring
spec:
    type: NodePort
    selector:
        app: grafana
    ports:
        - port: 3000
          targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        name: grafana
    name: grafana
    namespace: monitoring
spec:
    replicas: 1
    selector:
        matchLabels:
            name: grafana
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                name: grafana
        spec:
            containers:
                - image: grafana/grafana
                  imagePullPolicy: IfNotPresent
                  name: grafana
                  ports:
                      - containerPort: 3000
                        protocol: TCP
                  resources:
                      limits:
                          cpu: 4000m
                          memory: '6Gi'
                      requests:
                          cpu: 2000m
                          memory: '3Gi'
                  volumeMounts:
                      - mountPath: /var/lib/grafana
                        name: data
            restartPolicy: Always
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - emptyDir: {}
                  name: data
