apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provider
  namespace: monitoring
data:
  providers.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: false
      options:
        path: /var/lib/grafana/dashboards