apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: busybox1
    image: busybox
    command:
    - /bin/sh
    args:
    - -c
    - echo hello; sleep 3600 
  - name: busybox2
    image: busybox
    command:
    - /bin/sh
    args:
    - -c
    - echo hello; sleep 3600
  restartPolicy: Never
status: {}
