apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: monitoring
# spec:
#   type: NodePort
#   selector:
#     name: promtail
#   ports:
#     - port: 3200
#       targetPort: 3200