apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-storage-volume
spec:
  # storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi